app/author/views.py
from flask import (
    Blueprint,
    render_template,
    redirect,
    url_for,
    jsonify,
    flash,
    send_from_directory,
)
from flask_ckeditor import upload_success
from flask_login import (
    current_user,
    login_required,
)
import PIL, simplejson, traceback
from PIL import Image
from flask_rq import get_queue
from sqlalchemy.orm import Session

from app.models.users import *
from app.author.forms import *
from app.auth.forms import *
from app import db
from app.email import send_email
from app.models import User, Message, Memo, Recipient
from app.auth.email import send_password_reset_email, send_memo_received_email
from app.auth.admin_decorators import check_confirmed
from werkzeug import secure_filename
from app.lib.upload_file import uploadfile
from werkzeug.datastructures import FileStorage

ALLOWED_EXTENSIONS = {"txt", "gif", "png", "jpg", "jpeg", "bmp", "rar", "zip", "7zip", "doc", "docx", "pdf"}

author = Blueprint('author', __name__)
certificates = UploadSet("certificates", TEXT + DOCUMENTS + IMAGES)


@author.route('/')
@login_required
@check_confirmed
def dashboard():
    """Admin dashboard page."""
    sen_memos = Memo.query.filter_by(author_id=current_user.id).order_by(Memo.createdAt.desc()).limit(4)
    all_memos_sent = Memo.query.filter_by(author_id=current_user.id).all()
    recs = Recipient.query.filter_by(user_id=current_user.id) \
        .order_by(Recipient.createdAt.desc()).limit(4)
    screams = Memo.query.join(Recipient, (Recipient.memo_id == Memo.id))\
        .filter(Recipient.user_id == current_user.id).all()
    open_memos = Memo.query.filter_by(author_id=current_user.id, status='Open').all()

    return render_template('author/index.html', sen_memos=sen_memos, recs=recs, open_memos=open_memos,
                           screams=screams)


@author.route('/new_memo', methods=['post', 'get'])
@login_required
@check_confirmed
def new_memo():
    """Create memo."""
    form = MemoForm()
    if form.validate_on_submit():
        memo = Memo(
            public_id=str(uuid.uuid4()),
            memo_title=form.title.data,
            author_id=current_user.id,
            reference_number=form.reference_number.data,
            date_modified=form.date_modified.data
        )
        db.session.add(memo)
        db.session.commit()
        flash('Successfully added memo! Please indicate the recipient of this memo', 'success')
        return redirect(url_for('author.new_memo_assign', memo_id=memo.public_id))
    return render_template('author/add_new_memo.html', form=form)


@author.route('/new_memo/assign_recipient_zero/<memo_id>', methods=['post', 'get'])
@login_required
@check_confirmed
def new_memo_assign(memo_id):
    """Assign memo."""
    memo = Memo.query.filter_by(public_id=memo_id).first_or_404()
    form = RecipientForm()
    this_recipient = form.recipient.data
    if form.validate_on_submit():
        user = User.query.filter_by(id=this_recipient.id).first_or_404()
        recipient = Recipient(
            memo_id=memo.id,
            recipient_name=this_recipient.first_name,
            user_id=this_recipient.id
        )
        db.session.add(recipient)
        user.add_notification('unread_memo_count', user.new_memos())
        db.session.commit()
        send_memo_received_email(user)
        flash('Successfully added recipient to memo', 'success')
        return redirect(url_for('author.sent_memos'))
    return render_template('author/assign_recipient.html', form=form, memo=memo)


@author.route('/view_memo/<memo_id>', methods=['post', 'get'])
@login_required
@check_confirmed
def view_memo(memo_id):
    """View memo."""
    memo = Memo.query.filter_by(public_id=memo_id).first_or_404()
    first_recipient = Recipient.query.join(Memo, (Memo.id == Recipient.memo_id)).filter(
        Memo.public_id == memo_id).first()
    memo_recipients = Recipient.query.join(Memo, (Memo.id == Recipient.memo_id)).all()
    memo_comments = Comment.query.join(User, (User.id == Comment.user_id)).filter(Comment.memo_id == memo.id).all()
    date_added = memo.createdAt
    date_modified = memo.date_modified
    da = date_added.strftime('%d/%m/%Y')
    dm = date_modified.strftime('%d/%m/%Y')
    current_user.last_memo_read_time = datetime.utcnow()
    current_user.last_comment_read_time = datetime.utcnow()
    current_user.add_notification('unread_memo_count', 0)
    current_user.add_notification('unread_comment_count', 0)
    db.session.commit()

    return render_template('author/view_memo.html', memo=memo, da=da, dm=dm,
                           memo_recipients=memo_recipients, first_recipient=first_recipient,
                           memo_comments=memo_comments)


@author.route('/my_memos/received', methods=['post', 'get'])
@login_required
@check_confirmed
def received_memos():
    current_user.last_memo_read_time = datetime.utcnow()
    current_user.last_comment_read_time = datetime.utcnow()
    current_user.add_notification('unread_memo_count', 0)
    current_user.add_notification('unread_comment_count', 0)
    db.session.commit()
    recs = Recipient.query.join(User, (User.id == Recipient.user_id)).filter(User.id == current_user.id) \
        .order_by(Recipient.createdAt.desc()).all()
    screams = Memo.query.join(Recipient, (Recipient.memo_id == Memo.id)) \
        .filter(Recipient.user_id == current_user.id).all()
    return render_template('author/received_memos.html', recs=recs, screams=screams)


@author.route('/my_memos/sent', methods=['post', 'get'])
@login_required
@check_confirmed
def sent_memos():
    sen_memos = Memo.query.filter_by(author_id=current_user.id).order_by(Memo.createdAt.desc()).all()
    snames = Recipient.query.join(Memo, (Memo.id == Recipient.memo_id)).order_by(Recipient.createdAt.desc()).all()

    return render_template('author/sent_memos.html', sen_memos=sen_memos, snames=snames)


@author.route('/my_memos/forwarded', methods=['post', 'get'])
@login_required
@check_confirmed
def forwarded_memos():
    # recs = Recipient.query.filter_by(rec_id=current_user.id).all()
    # fmemos = Memo.query.join(Recipient, (Recipient.memo_id == Memo.id)).all()
    # fnames = User.query.join(Recipient, (Recipient.forwarded_from == User.id)).order_by(User.createdAt.desc()).all()
    # ftnames = User.query.join(Recipient, (Recipient.rec_id == User.id)).order_by(User.createdAt.desc()).all()

    return render_template('author/forwarded_memos.html'
                           )


@author.route('/add_comment/<memo_id>', methods=['post', 'get'])
@login_required
@check_confirmed
def add_comment(memo_id):
    memo = Memo.query.filter_by(public_id=memo_id).first_or_404()
    form = CommentForm()
    this_recipient = form.recipient_id.data
    if form.validate_on_submit():
        existing_rec = Recipient.query.join(Memo, (memo.id == Recipient.memo_id)) \
            .filter(Recipient.user_id == this_recipient.id).first()
        if existing_rec is None:
            added_recipient = Recipient(
                memo_id=memo.id,
                recipient_name=this_recipient.first_name,
                user_id=this_recipient.id
            )
            db.session.add(added_recipient)
            added_comment = Comment(
                user_id=current_user.id,
                comment_body=form.comment_body.data,
                memo_id=memo.id,
                sent_to=this_recipient.first_name
            )
            db.session.add(added_comment)
        else:
            added_comment = Comment(
                user_id=current_user.id,
                comment_body=form.comment_body.data,
                memo_id=memo.id,
                sent_to=this_recipient.first_name
            )
            db.session.add(added_comment)
        db.session.commit()
        flash('Successfully added comment to memo', 'success')
        return redirect(url_for('author.view_memo', memo_id=memo.public_id))
    return render_template('author/add_new_comment.html', form=form, memo=memo)


@author.route('/my_memos/close_cycle/<memo_id>', methods=['post', 'get'])
@login_required
@check_confirmed
def close_memo_cycle(memo_id):
    closed_memo = Memo.query.filter_by(public_id=memo_id).first_or_404()
    if closed_memo.author.email == current_user.email:
        flash("Cannot change the status of this memo yet", "warning")
        return redirect(url_for("author.sent_memos"))
    elif current_user.role.index != 'qam':
        flash("Cannot change the status of this memo yet", "warning")
        return redirect(url_for("author.received_memos"))
    else:
        if closed_memo.status == 'Open':
            closed_memo.status = 'Closed'
        else:
            closed_memo.status = 'Open'
        db.session.commit()
        flash("Successfully updated memo status", "success")
        return redirect(url_for("author.received_memos"))


@author.route('/notifications')
@login_required
@check_confirmed
def notifications():
    since = request.args.get('since', 0.0, type=float)
    notifications = current_user.notifications.filter(
        Notification.timestamp > since).order_by(Notification.timestamp.asc())
    return jsonify([{
        'name': n.name,
        'data': n.get_data(),
        'timestamp': n.timestamp
    } for n in notifications])


@author.route('/clear_notifications', methods=['post', 'get'])
@login_required
@check_confirmed
def clear_notifications():
    current_user.add_notification('unread_memo_count', 0)
    current_user.add_notification('unread_comment_count', 0)
    db.session.commit()


@author.route('/profile', methods=['post', 'get'])
@login_required
@check_confirmed
def profile():
    """Admin dashboard page."""

    form = ProfileForm(obj=current_user)

    if form.validate_on_submit():
        form.populate_obj(current_user)
        db.session.commit()
        return redirect(url_for('author.profile'))
    return render_template('author/user-profile-page.html', form=form)


@author.route('/settings', methods=['post', 'get'])
@login_required
@check_confirmed

app/templates/layouts/admin_base.html
{% import 'macros/admin_nav_macros.html' as sidebar %}
{% import 'macros/header_macros.html' as header %}
{% import 'macros/footer_macros.html' as footer %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% include 'partials/_head.html' %} {# Any templates that extend this
    template can set custom_head_tags to add scripts to their page #}
    {% block custom_head_tags %}

    {% endblock %}
</head>
<body class="sidebar-dark">
<div class="main-wrapper">
    <!-- START NAV -->
    {% set dropdown = [
        ('All Users', [
            ('admin.registered_users', 'All Users', 'users'),
            ('admin.new_user', 'Add Users', 'user-plus'),
            ('admin.invite_user', 'Invite Users', 'user-plus'),
            ('admin.admin_settings', 'Settings', 'settings')
            ], '','users')
    ] %}
    {% block sidebar %}
        {{ sidebar.render_sidebar(current_user, dropdown) }}
    {% endblock %}

    <!-- END NAV -->
    <!-- START WRAPPER -->
    <div class="page-wrapper">
        {% block header %}
        {{ header.render_header(current_user) }}
        {% endblock %}
        <div class="page-content">

            {% include 'partials/_flashes.html' %}
            {# When extended, the content block contains all the html of the webpage #}

            {% block content %}
            {% endblock %}

        </div>
        {% block footer %}
        {{ footer.render_footer(current_user) }}
        {% endblock %}
    </div>
    <!-- END WRAPPER -->
</div>

{# Implement CSRF protection for site #} {% if csrf_token()|safe %}
<div style="visibility: hidden; display: none">
    <input
            type="hidden"
            name="csrf_token"
            value="{{ csrf_token()|safe }}"
    />
</div>
{% endif %}
{% block dash_scripts %}
<!--
  ================================================
  Scripts
  ================================================
-->
<!-- core:js -->
<script src="{{ url_for('static', filename='vendors/core/core.js') }}"></script>
<!-- endinject -->
<!-- plugin js for this page -->
<script src="{{ url_for('static', filename='vendors/chartjs/Chart.min.js') }}"></script>
<script src="{{ url_for('static', filename='vendors/jquery.flot/jquery.flot.js') }}"></script>
<script src="{{ url_for('static', filename='vendors/jquery.flot/jquery.flot.resize.js') }}"></script>
<script src="{{ url_for('static', filename='vendors/bootstrap-datepicker/bootstrap-datepicker.min.js') }}"></script>
<script src="{{ url_for('static', filename='vendors/apexcharts/apexcharts.min.js') }}"></script>
<script src="{{ url_for('static', filename='vendors/progressbar.js/progressbar.min.js') }}"></script>
<!-- end plugin js for this page -->
<!-- inject:js -->
<script src="{{ url_for('static', filename='vendors/feather-icons/feather.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/template.js') }}"></script>
<!-- endinject -->

<script type="text/javascript"
        src="{{ url_for('static', filename='vendors/sweetalert/dist/sweetalert.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='vendors/dropify/js/dropify.min.js') }}"></script>
{{ moment.include_moment() }} {{ moment.lang(g.locale) }}
{% endblock %}
<!-- custom js for this page -->
{% block scripts %}

{% endblock %}
{{ moment.include_moment() }} {{ moment.lang(g.locale) }}
<script>

    $(document).ready(function () {
        $('#select-author').change(function(){
            var value = $(this).val();
            $("td.user.role:contains(" + value + ")")
              .closest("tr")
              .removeClass("hidden")
              .show();
            $("td.user.role")
              .not(":contains(" + value + ")")
              .closest("tr")
              .addClass("hidden")
              .hide();
        });
    });
</script>
</body>
</html>

app/templates/layouts/base.html
{% import 'macros/header_macros.html' as header with context %}
{% import 'macros/footer_macros.html' as footer %}
{% import 'macros/sidebar_macros.html' as sidebar %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% include 'partials/_head.html' %} {# Any templates that extend this
    template can set custom_head_tags to add scripts to their page #}
    {% block custom_head_tags %}

    {% endblock %}
</head>
<body class="sidebar-dark">
    <div class="main-wrapper">
        <!-- START NAV -->
        {% block sidebar %}
            {{ sidebar.render_sidebar(current_user, dropdown) }}
        {% endblock %}
        <!-- END NAV -->

        <!-- START WRAPPER -->
        <div class="page-wrapper">
            {% block header %}
                {{ header.render_header(current_user) }}
            {% endblock %}
            <div class="page-content">
            {% include 'partials/_flashes.html' %}
            <!-- START CONTENT -->
            {# When extended, the content block contains all the html of the webpage #}

            {% block content %}
            {% endblock %}
            <!-- END CONTENT -->
            <!--
              ////////////////////////////////////////////////////////////////////////////
            -->
            </div>
            {% block footer %}
                {{ footer.render_footer(current_user) }}
            {% endblock %}
        </div>
        <!-- END WRAPPER -->
    </div>


    {# Implement CSRF protection for site #}
    {% if csrf_token()|safe %}
    <div style="visibility: hidden; display: none">
        <input type="hidden" name="csrf_token" value="{{ csrf_token()|safe }}"/>
    </div>
    {% endif %}


{% block dash_scripts %}
    <!--
      ================================================
      Scripts
      ================================================
    -->
    <!-- core:js -->
    <script src="{{ url_for('static', filename='vendors/core/core.js') }}"></script>
    <!-- endinject -->
    <!-- plugin js for this page -->
    <script src="{{ url_for('static', filename='vendors/chartjs/Chart.min.js') }}"></script>
    <script src="{{ url_for('static', filename='vendors/jquery.flot/jquery.flot.js') }}"></script>
    <script src="{{ url_for('static', filename='vendors/jquery.flot/jquery.flot.resize.js') }}"></script>
    <script src="{{ url_for('static', filename='vendors/bootstrap-datepicker/bootstrap-datepicker.min.js') }}"></script>
    <script src="{{ url_for('static', filename='vendors/apexcharts/apexcharts.min.js') }}"></script>
    <script src="{{ url_for('static', filename='vendors/progressbar.js/progressbar.min.js') }}"></script>
    <!-- end plugin js for this page -->
    <!-- inject:js -->
    <script src="{{ url_for('static', filename='vendors/feather-icons/feather.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/template.js') }}"></script>
    <!-- endinject -->

    <script type="text/javascript" src="{{ url_for('static', filename='vendors/sweetalert/dist/sweetalert.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='vendors/dropify/js/dropify.min.js') }}"></script>
    {{ moment.include_moment() }} {{ moment.lang(g.locale) }}
{% endblock %}
    <!-- custom js for this page -->
{% block scripts %}

{% endblock %}
    <!-- end custom js for this page -->
    {% if current_user.is_authenticated %}

    {% endif %}
    <script>
        function delete_memo(id) {
            swal({
                    title: "Are you sure?",
                    text: "You will not be able to recover this file!",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonColor: "#DD6B55",
                    confirmButtonText: "Yes, delete it!",
                    closeOnConfirm: false
                },
                function () {
                    $(id).submit();
                });
        }

        var csrftoken = "{{ csrf_token() }}";

        $.ajaxSetup({
            beforeSend: function (xhr, settings) {
                if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken)
                }
            }
        });


        function get_profile(id) {
            $.get().done(function (response) {
                $('#profile-placehold').html(response);
            }).fail(function (XMLHttpRequest, textStatus, errorThrown) {
                swal("Status: " + textStatus, "Error: " + errorThrown, "error");
            });
        }


        function set_memo_count(n) {
            $('#memo_count').text(n);
            $('#memo_count').css('visibility', n ? 'visible' : 'hidden');
        }
        function set_comment_count(n) {
            $('#comment_count').text(n);
            $('#comment_count').css('visibility', n ? 'visible' : 'hidden');
        }

        {% if current_user.is_authenticated %}
        $(function() {
            var since = 0;
            setInterval(function() {
                $.ajax('{{ url_for('author.notifications') }}?since=' + since).done(
                    function(notifications) {
                        for (var i = 0; i < notifications.length; i++) {
                            if (notifications[i].name == 'unread_memo_count') {
                                set_memo_count(notifications[i].data);
                            } else if (notifications[i].name == 'unread_comment_count') {
                                set_comment_count(notifications[i].data);
                            }
                            since = notifications[i].timestamp;
                        }
                    }
                );
            }, 10000);
        });
        {% endif %}
        function set_notification_count(n) {
        $('#notification_count').text(n);
        $('#notification_count').css('visibility', n ? 'visible' : 'hidden');
        if (n > 0){
            $.ajax('{{ url_for('author.notifications') }}').done(function(data) {
              $('#notificationDropdown').html(data)
            });
          }
        }

      function notification(id){
        $(id).dropdown();
      }

    </script>
</body>
</html>