app/models/memos.py
from datetime import datetime

from .. import db


class Memo(db.Model):
    __tablename__ = 'memos'
    id = db.Column(db.Integer, primary_key=True)
    public_id = db.Column(db.String(100), unique=True)
    author_id = db.Column(db.Integer(), db.ForeignKey('users.id'))
    file_id = db.Column(db.Integer(), db.ForeignKey('files.id'))
    memo_title = db.Column(db.Text())
    folio = db.Column(db.String(64), index=True)
    reference_number = db.Column(db.String(256), index=True)
    status = db.Column(db.String(64), index=True, default='Open')
    date_modified = db.Column(db.DateTime())

    recipients = db.relationship('Recipient', backref='memo', lazy='dynamic')
    comments = db.relationship('Comment', backref='memo', uselist=False)
    timestamp = db.Column(db.DateTime(), default=datetime.utcnow)
    createdAt = db.Column(db.DateTime(), default=datetime.utcnow)
    updatedAt = db.Column(db.DateTime(), default=datetime.utcnow, onupdate=datetime.utcnow)

    def __repr__(self):
        return '<Memo {}>'.format(self.reference_number)

app/author/forms.py
from flask import url_for
from flask_wtf import Form, FlaskForm
from wtforms.ext.sqlalchemy.fields import QuerySelectField, QuerySelectMultipleField
from wtforms import ValidationError
from wtforms.fields import (
    BooleanField,
    PasswordField,
    StringField,
    SubmitField,
    TextField,
    DateField,
    DecimalField,
    SelectField,
    TextAreaField,
    IntegerField,
    FileField)
from wtforms import RadioField
from wtforms.fields.html5 import EmailField
from wtforms.validators import Email, EqualTo, InputRequired, Length, DataRequired
from flask_wtf.file import FileField, FileRequired, FileAllowed
from flask_uploads import UploadSet, configure_uploads, DOCUMENTS, IMAGES, TEXT
from flask_login import current_user
from app.models import User
from app.models import *

certificates = UploadSet("certificates", TEXT + DOCUMENTS + IMAGES)


def get_pk(obj):
    return str(obj)


class ProfileForm(FlaskForm):
    first_name = StringField(
        'First name', validators=[InputRequired(),
                                  Length(1, 64)])
    surname = StringField(
        'Surname', validators=[InputRequired(),
                               Length(1, 64)])
    email = EmailField(
        'Email', validators=[InputRequired(),
                             Length(1, 64),
                             Email()])
    address = StringField('Address')
    dob = DateField('Date Of Birth', validators=[DataRequired()], format='%d/%m/%Y')

    submit = SubmitField('Submit')


class MemoForm(FlaskForm):
    author_id = IntegerField('Author')
    title = TextAreaField('Title')
    reference_number = StringField(
        'Reference Number', validators=[InputRequired(),
                                        Length(1, 64)])
    folio = StringField(
        'Folio')
    date_modified = DateField('Date', validators=[DataRequired()], format='%d/%m/%Y')

    submit = SubmitField('Submit')


class AuthorForm(FlaskForm):
    name = TextAreaField('Name')
    submit = SubmitField('Submit')


class RecipientForm(FlaskForm):
    recipient_name = StringField('Recipient Name')
    memo_id = IntegerField('Memo')
    recipient = QuerySelectField(
        'Recipient',
        validators=[InputRequired()],
        get_label='first_name',
        query_factory=lambda: db.session.query(User).order_by('first_name'), get_pk=get_pk)
    submit = SubmitField('Submit')


class CommentForm(FlaskForm):
    comment_body = TextAreaField(
        'Comment Body', validators=[InputRequired(),
                                    Length(1, 200)])
    recipient_id = QuerySelectField(
        'Recipient',
        get_label='first_name',
        query_factory=lambda: db.session.query(User), get_pk=get_pk)
    submit = SubmitField('Add')

app/author/__init__.py
from app.author.views import author

app/author/views.py
from flask import (
    Blueprint,
    render_template,
    redirect,
    url_for,
    jsonify,
    flash,
    send_from_directory,
)
from flask_ckeditor import upload_success
from flask_login import (
    current_user,
    login_required,
)
import PIL, simplejson, traceback
from PIL import Image
from flask_rq import get_queue
from sqlalchemy.orm import Session

from app.models.users import *
from app.author.forms import *
from app.auth.forms import *
from app import db
from app.email import send_email
from app.models import User, Message, Memo, Recipient
from app.auth.email import send_password_reset_email, send_memo_received_email
from app.auth.admin_decorators import check_confirmed
from werkzeug import secure_filename
from app.lib.upload_file import uploadfile
from werkzeug.datastructures import FileStorage

ALLOWED_EXTENSIONS = {"txt", "gif", "png", "jpg", "jpeg", "bmp", "rar", "zip", "7zip", "doc", "docx", "pdf"}

author = Blueprint('author', __name__)
certificates = UploadSet("certificates", TEXT + DOCUMENTS + IMAGES)


@author.route('/')
@login_required
@check_confirmed
def dashboard():
    """Admin dashboard page."""
    sen_memos = Memo.query.filter_by(author_id=current_user.id).order_by(Memo.createdAt.desc()).limit(4)
    all_memos_sent = Memo.query.filter_by(author_id=current_user.id).all()
    recs = Recipient.query.filter_by(user_id=current_user.id) \
        .order_by(Recipient.createdAt.desc()).limit(4)
    screams = Memo.query.join(Recipient, (Recipient.memo_id == Memo.id))\
        .filter(Recipient.user_id == current_user.id).all()
    open_memos = Memo.query.filter_by(author_id=current_user.id, status='Open').all()

    return render_template('author/index.html', sen_memos=sen_memos, recs=recs, open_memos=open_memos,
                           screams=screams)


@author.route('/new_memo', methods=['post', 'get'])
@login_required
@check_confirmed
def new_memo():
    """Create memo."""
    form = MemoForm()
    if form.validate_on_submit():
        memo = Memo(
            public_id=str(uuid.uuid4()),
            memo_title=form.title.data,
            author_id=current_user.id,
            reference_number=form.reference_number.data,
            date_modified=form.date_modified.data
        )
        db.session.add(memo)
        db.session.commit()
        flash('Successfully added memo! Please indicate the recipient of this memo', 'success')
        return redirect(url_for('author.new_memo_assign', memo_id=memo.public_id))
    return render_template('author/add_new_memo.html', form=form)


@author.route('/new_memo/assign_recipient_zero/<memo_id>', methods=['post', 'get'])
@login_required
@check_confirmed
def new_memo_assign(memo_id):
    """Assign memo."""
    memo = Memo.query.filter_by(public_id=memo_id).first_or_404()
    form = RecipientForm()
    this_recipient = form.recipient.data
    if form.validate_on_submit():
        user = User.query.filter_by(id=this_recipient.id).first_or_404()
        recipient = Recipient(
            memo_id=memo.id,
            recipient_name=this_recipient.first_name,
            user_id=this_recipient.id
        )
        db.session.add(recipient)
        user.add_notification('unread_memo_count', user.new_memos())
        db.session.commit()
        send_memo_received_email(user)
        flash('Successfully added recipient to memo', 'success')
        return redirect(url_for('author.sent_memos'))
    return render_template('author/assign_recipient.html', form=form, memo=memo)


@author.route('/view_memo/<memo_id>', methods=['post', 'get'])
@login_required
@check_confirmed
def view_memo(memo_id):
    """View memo."""
    memo = Memo.query.filter_by(public_id=memo_id).first_or_404()
    first_recipient = Recipient.query.join(Memo, (Memo.id == Recipient.memo_id)).filter(
        Memo.public_id == memo_id).first()
    memo_recipients = Recipient.query.join(Memo, (Memo.id == Recipient.memo_id)).all()
    memo_comments = Comment.query.join(User, (User.id == Comment.user_id)).filter(Comment.memo_id == memo.id).all()
    date_added = memo.createdAt
    date_modified = memo.date_modified
    da = date_added.strftime('%d/%m/%Y')
    dm = date_modified.strftime('%d/%m/%Y')
    current_user.last_memo_read_time = datetime.utcnow()
    current_user.last_comment_read_time = datetime.utcnow()
    current_user.add_notification('unread_memo_count', 0)
    current_user.add_notification('unread_comment_count', 0)
    db.session.commit()

    return render_template('author/view_memo.html', memo=memo, da=da, dm=dm,
                           memo_recipients=memo_recipients, first_recipient=first_recipient,
                           memo_comments=memo_comments)


@author.route('/my_memos/received', methods=['post', 'get'])
@login_required
@check_confirmed
def received_memos():
    current_user.last_memo_read_time = datetime.utcnow()
    current_user.last_comment_read_time = datetime.utcnow()
    current_user.add_notification('unread_memo_count', 0)
    current_user.add_notification('unread_comment_count', 0)
    db.session.commit()
    recs = Recipient.query.join(User, (User.id == Recipient.user_id)).filter(User.id == current_user.id) \
        .order_by(Recipient.createdAt.desc()).all()
    screams = Memo.query.join(Recipient, (Recipient.memo_id == Memo.id)) \
        .filter(Recipient.user_id == current_user.id).all()
    return render_template('author/received_memos.html', recs=recs, screams=screams)


@author.route('/my_memos/sent', methods=['post', 'get'])
@login_required
@check_confirmed
def sent_memos():
    sen_memos = Memo.query.filter_by(author_id=current_user.id).order_by(Memo.createdAt.desc()).all()
    snames = Recipient.query.join(Memo, (Memo.id == Recipient.memo_id)).order_by(Recipient.createdAt.desc()).all()

    return render_template('author/sent_memos.html', sen_memos=sen_memos, snames=snames)


@author.route('/my_memos/forwarded', methods=['post', 'get'])
@login_required
@check_confirmed
def forwarded_memos():
    # recs = Recipient.query.filter_by(rec_id=current_user.id).all()
    # fmemos = Memo.query.join(Recipient, (Recipient.memo_id == Memo.id)).all()
    # fnames = User.query.join(Recipient, (Recipient.forwarded_from == User.id)).order_by(User.createdAt.desc()).all()
    # ftnames = User.query.join(Recipient, (Recipient.rec_id == User.id)).order_by(User.createdAt.desc()).all()

    return render_template('author/forwarded_memos.html'
                           )


@author.route('/add_comment/<memo_id>', methods=['post', 'get'])
@login_required
@check_confirmed
def add_comment(memo_id):
    memo = Memo.query.filter_by(public_id=memo_id).first_or_404()
    form = CommentForm()
    this_recipient = form.recipient_id.data
    if form.validate_on_submit():
        existing_rec = Recipient.query.join(Memo, (memo.id == Recipient.memo_id)) \
            .filter(Recipient.user_id == this_recipient.id).first()
        if existing_rec is None:
            added_recipient = Recipient(
                memo_id=memo.id,
                recipient_name=this_recipient.first_name,
                user_id=this_recipient.id
            )
            db.session.add(added_recipient)
            added_comment = Comment(
                user_id=current_user.id,
                comment_body=form.comment_body.data,
                memo_id=memo.id,
                sent_to=this_recipient.first_name
            )
            db.session.add(added_comment)
        else:
            added_comment = Comment(
                user_id=current_user.id,
                comment_body=form.comment_body.data,
                memo_id=memo.id,
                sent_to=this_recipient.first_name
            )
            db.session.add(added_comment)
        db.session.commit()
        flash('Successfully added comment to memo', 'success')
        return redirect(url_for('author.view_memo', memo_id=memo.public_id))
    return render_template('author/add_new_comment.html', form=form, memo=memo)


@author.route('/my_memos/close_cycle/<memo_id>', methods=['post', 'get'])
@login_required
@check_confirmed
def close_memo_cycle(memo_id):
    closed_memo = Memo.query.filter_by(public_id=memo_id).first_or_404()
    if closed_memo.author.email == current_user.email:
        flash("Cannot change the status of this memo yet", "warning")
        return redirect(url_for("author.sent_memos"))
    elif current_user.role.index != 'qam':
        flash("Cannot change the status of this memo yet", "warning")
        return redirect(url_for("author.received_memos"))
    else:
        if closed_memo.status == 'Open':
            closed_memo.status = 'Closed'
        else:
            closed_memo.status = 'Open'
        db.session.commit()
        flash("Successfully updated memo status", "success")
        return redirect(url_for("author.received_memos"))


@author.route('/notifications')
@login_required
@check_confirmed
def notifications():
    since = request.args.get('since', 0.0, type=float)
    notifications = current_user.notifications.filter(
        Notification.timestamp > since).order_by(Notification.timestamp.asc())
    return jsonify([{
        'name': n.name,
        'data': n.get_data(),
        'timestamp': n.timestamp
    } for n in notifications])


@author.route('/clear_notifications', methods=['post', 'get'])
@login_required
@check_confirmed
def clear_notifications():
    current_user.add_notification('unread_memo_count', 0)
    current_user.add_notification('unread_comment_count', 0)
    db.session.commit()


@author.route('/profile', methods=['post', 'get'])
@login_required
@check_confirmed
def profile():
    """Admin dashboard page."""

    form = ProfileForm(obj=current_user)

    if form.validate_on_submit():
        form.populate_obj(current_user)
        db.session.commit()
        return redirect(url_for('author.profile'))
    return render_template('author/user-profile-page.html', form=form)


@author.route('/settings', methods=['post', 'get'])
@login_required
@check_confirmed

app/templates/author/_memo.html
<div class="dropdown-menu" aria-labelledby="messageDropdown">
    <div class="dropdown-header d-flex align-items-center justify-content-between">
        <p class="mb-0 font-weight-medium">{{ new_memos }} New Message(s)</p>
    </div>
    <div class="dropdown-body">
        {% for item in notifications %}
        <a href="{{ url_for('author.view_memo', memo_id=item.public_id)}}" class="dropdown-item">
            <div class="figure">
                <img src="https://via.placeholder.com/30x30" alt="userr">
            </div>
            <div class="content">
                <div class="d-flex justify-content-between align-items-center">
                    <p>{{item.memo_title}}</p>
                    <p class="sub-text text-muted">{{item.createdAt.strftime('%d/%m/%Y')}}</p>
                </div>
                <p class="sub-text text-muted">{{item.reference_number}}</p>
            </div>
        </a>
        {%else%}
        <a href="javascript:;" class="dropdown-item">
            <div class="content">
                <p class="sub-text text-muted">No New Memos</p>
            </div>
        </a>
        {%endfor%}
    </div>
    <div class="dropdown-footer d-flex align-items-center justify-content-center">
        <a href="{{url_for('author.received_memos')}}">View all</a>
    </div>
</div>

app/templates/author/_notification.html
<div class="dropdown-menu" aria-labelledby="notificationDropdown">
    <div class="dropdown-header d-flex align-items-center justify-content-between">
        <p class="mb-0 font-weight-medium">New Notifications</p>
        <a href="javascript:;" class="text-muted">Clear all</a>
    </div>
    <div class="dropdown-body">
         {% for item in comments %}
        <a href="{{ url_for('author.view_memo', memo_id=item.memo.public_id)}}" class="dropdown-item">
            <div class="icon">
                <i data-feather="user-plus"></i>
            </div>
            <div class="content">
                <p>New comment from {{ item.user.full_name() }}</p>
                <p>{{item.comment_body}}</p>
                <p class="sub-text text-muted">{{item.createdAt.strftime('%d/%m/%Y')}}</p>
            </div>
        </a>
        {% else %}
        <a href="javascript:;" class="dropdown-item">
            <div class="icon">
                <i data-feather="user-plus"></i>
            </div>
            <div class="content">
                <p>No new comments</p>
                <p class="sub-text text-muted">2 sec ago</p>
            </div>
        </a>
        {% endfor %}
    </div>
</div>

app/templates/author/forwarded_memos.html
{% extends 'layouts/base.html' %}
{% block custom_head_tags %}
<!-- CORE CSS-->
<link rel="stylesheet"
      href="{{ url_for('static', filename='vendors/bootstrap-datepicker/bootstrap-datepicker.min.css') }}">

{% endblock %}

{% block content %}
<nav class="page-breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#">CREATE</a></li>
        <li class="breadcrumb-item active" aria-current="page">New Comment</li>
    </ol>
</nav>

<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <div class="d-flex justify-content-between align-items-baseline mb-lg-4">
                  <h6 class="card-title mb-0">Forwaded Memos</h6>
                </div>
                <div class="table-responsive">
                        <table class="table table-hover mb-0">
                            <thead>
                            <tr>
                                <th class="pt-0">#</th>
                                <th class="pt-0">Memo Ref. No.</th>
                                <th class="pt-0">Forwaded From</th>
                                <th class="pt-0">Forwaded To</th>
                                <th class="pt-0">Memo Title</th>
                                <th class="pt-0">Status</th>
                                <th class="pt-0">Comment</th>
                                <th class="pt-0">Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for memo in fmemos %}
                            <tr>
                                <td>{{loop.index}}</td>
                                <td><a href="{{ url_for('author.view_memo', memo_id=memo.id) }}">{{memo.reference_number}}</a>
                                </td>
                                <td><a href="#">{{fnames[0].first_name if fnames}}</a></td>
                                <td><a href="#">{{ ftnames[0].first_name if ftnames }}</a></td>
                                <td>{{memo.title}}</td>
                                <td>
                                    {% if memo.status == 'Open' %}
                                    <span class="badge badge-info-muted">Open</span>
                                    {%else%}
                                    <span class="badge badge-success">Closed</span>
                                    {% endif %}
                                </td>
                                <td>
                                    <a href="{{ url_for('author.add_comment', memo_id=memo.id) }}"
                                       class="btn btn-primary">Comment</a>
                                </td>
                                <td>{% if memo.status == 'Open' %}
                                    <a href="{{ url_for('author.close_memo_cycle', memo_id=memo.id) }}"
                                       class="btn btn-danger">Close</a>
                                    {% else %}
                                    <a href="{{ url_for('author.close_memo_cycle', memo_id=memo.id) }}"
                                       class="btn btn-success">Open</a>
                                    {%endif%}
                                </td>

                            </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

app/templates/author/received_memos.html
{% extends 'layouts/base.html' %}
{% block custom_head_tags %}
<link rel="stylesheet"
      href="{{ url_for('static', filename='vendors/bootstrap-datepicker/bootstrap-datepicker.min.css') }}">
<!-- plugin css for this page -->
<link rel="stylesheet" href="{{ url_for('static', filename='vendors/prismjs/themes/prism.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='vendors/datatables.net-bs4/dataTables.bootstrap4.css') }}">
<!-- end plugin css for this page -->
{% endblock %}

{% block content %}
<nav class="page-breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#">RECIEVED</a></li>
        <li class="breadcrumb-item active" aria-current="page">New Memos</li>
    </ol>
</nav>

<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <div class="d-flex justify-content-between align-items-baseline mb-lg-4">
                  <h6 class="card-title mb-0">Received Memos</h6>
                </div>
                <div class="table-responsive">
                        <table id="dataTable" class="table table-hover mb-0">
                            <thead>
                            <tr>
                                <th class="pt-0">#</th>
                                <th class="pt-0">Memo Ref. No.</th>
                                <th class="pt-0">Memo Title</th>
                                <th class="pt-0">File</th>
                                <th class="pt-0">Status</th>
                                <th class="pt-0">Comment</th>
                                <th class="pt-0">Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for memo in screams %}
                            <tr>
                                <td>{{loop.index}}</td>
                                <td><a href="{{ url_for('author.view_memo', memo_id=memo.public_id) }}">{{memo.reference_number}}</a>
                                </td>
                                <td>{{memo.memo_title}}</td>
                                <td>{{memo.file.subject}}</td>
                                <td>
                                    {% if memo.status == 'Open' %}
                                    <span class="badge badge-info-muted">Open</span>
                                    {%else%}
                                    <span class="badge badge-success">Closed</span>
                                    {% endif %}
                                </td>
                                <td>
                                    <a href="{% if current_user.is_authenticated and current_user.role.index == 'author'%}
                                    {{ url_for('author.add_comment', memo_id=memo.public_id) }}
                                       {% elif current_user.is_authenticated and current_user.role.index == 'qam' %}
                                       {{ url_for('qam.add_comment', memo_id=memo.public_id) }}
                                       {%endif%}"
                                       class="btn btn-primary">Comment</a>
                                </td>
                                <td>{% if memo.status == 'Open' %}
                                    <a href="{{ url_for('author.close_memo_cycle', memo_id=memo.public_id) }}"
                                       class="btn btn-danger {% if memo.author.email == current_user.email %} disabled {% endif %}">Close</a>
                                    {% else %}
                                    <a href="{{ url_for('author.close_memo_cycle', memo_id=memo.public_id) }}"
                                       class="btn btn-success {% if current_user.id != memo.author_id%}disabled{%endif%}">Open</a>
                                    {%endif%}
                                </td>
                            </tr>
                            {% else %}
                            <tr>
                             <td>No memos received</td>
                            </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block scripts %}
<!-- plugin js for this page -->
<script src="{{ url_for('static', filename='vendors/prismjs/prism.js') }}"></script>
<script src="{{ url_for('static', filename='vendors/clipboard/clipboard.min.js') }}"></script>
<script src="{{ url_for('static', filename='vendors/datatables.net/jquery.dataTables.js') }}"></script>
<script src="{{ url_for('static', filename='vendors/datatables.net-bs4/dataTables.bootstrap4.js') }}"></script>
<!-- end plugin js for this page -->
<script>
    $(function () {
        'use strict';

        $(function () {
            $('#dataTable').DataTable({
                "aLengthMenu": [
                    [10, 30, 50, -1],
                    [10, 30, 50, "All"]
                ],
                "iDisplayLength": 10,
                "language": {
                    search: ""
                }
            });
            $('#dataTable').each(function () {
                var datatable = $(this);
                // SEARCH - Add the placeholder for Search and Turn this into in-line form control
                var search_input = datatable.closest('.dataTables_wrapper').find('div[id$=_filter] input');
                search_input.attr('placeholder', 'Search');
                search_input.removeClass('form-control-sm');
                // LENGTH - Inline-Form control
                var length_sel = datatable.closest('.dataTables_wrapper').find('div[id$=_length] select');
                length_sel.removeClass('form-control-sm');
            });
        });

    });
</script>
{% endblock %}

app/templates/author/sent_memos.html
{% extends 'layouts/base.html' %}
{% block custom_head_tags %}
<!-- CORE CSS-->
<link rel="stylesheet"
      href="{{ url_for('static', filename='vendors/bootstrap-datepicker/bootstrap-datepicker.min.css') }}">
<!-- plugin css for this page -->
<link rel="stylesheet" href="{{ url_for('static', filename='vendors/prismjs/themes/prism.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='vendors/datatables.net-bs4/dataTables.bootstrap4.css') }}">
<!-- end plugin css for this page -->
{% endblock %}

{% block content %}
<div class="d-flex justify-content-between align-items-center flex-wrap grid-margin">
    <nav class="page-breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">VIEW</a></li>
            <li class="breadcrumb-item active" aria-current="page">My Memos</li>
        </ol>
    </nav>
     <div class="d-flex align-items-center flex-wrap text-nowrap">
        <a href="{{ url_for('author.new_memo')}}" type="button" class="btn btn-primary">ADD MEMO</a>
    </div>
</div>

<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <div class="d-flex justify-content-between align-items-baseline mb-lg-4">
                  <h6 class="card-title mb-0">Sent Memos</h6>
                </div>

                <div class="table-responsive">
                        <table id="dataTable" class="table table-hover mb-0">
                            <thead>
                            <tr>
                                <th class="pt-0">#</th>
                                <th class="pt-0">Memo Ref. No.</th>
                                <th class="pt-0">Memo Title</th>
                                <th class="pt-0">File</th>
                                <th class="pt-0">Status</th>
                                <th class="pt-0">Comment</th>
                                <th class="pt-0">Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for memo in sen_memos %}
                            <tr>
                                <td>{{loop.index}}</td>
                                <td><a href="{{ url_for('author.view_memo', memo_id=memo.public_id) }}">{{memo.reference_number}}</a>
                                </td>
                                </td>
                                <td>{{memo.memo_title}}</td>
                                <td>{{memo.file.subject}}</td>
                                <td>
                                    {% if memo.status == 'Open' %}
                                    <span class="badge badge-info-muted">Open</span>
                                    {%else%}
                                    <span class="badge badge-success">Closed</span>
                                    {% endif %}
                                </td>
                                <td>
                                    <a href="{{ url_for('author.add_comment', memo_id=memo.public_id) }}"
                                       class="btn btn-primary">Comment</a>
                                </td>
                                <td>{% if memo.status == 'Open' %}
                                    <a href="{{ url_for('author.close_memo_cycle', memo_id=memo.public_id) }}"
                                       class="btn btn-danger {% if memo.author.email == current_user.email %} disabled {% endif %}">Close</a>
                                    {% else %}
                                    <a href="{{ url_for('author.close_memo_cycle', memo_id=memo.public_id) }}"
                                       class="btn btn-success">Open</a>
                                    {%endif%}
                                </td>

                            </tr>
                            {% else %}
                            <tr>
                                <td><span style="color: #007bff;">No memos sent</span></td>
                            </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}
{% block scripts %}
<!-- plugin js for this page -->
<script src="{{ url_for('static', filename='vendors/prismjs/prism.js') }}"></script>
<script src="{{ url_for('static', filename='vendors/clipboard/clipboard.min.js') }}"></script>
<script src="{{ url_for('static', filename='vendors/datatables.net/jquery.dataTables.js') }}"></script>
<script src="{{ url_for('static', filename='vendors/datatables.net-bs4/dataTables.bootstrap4.js') }}"></script>
<!-- end plugin js for this page -->
<script>
    $(function () {
        'use strict';

        $(function () {
            $('#dataTable').DataTable({
                "aLengthMenu": [
                    [10, 30, 50, -1],
                    [10, 30, 50, "All"]
                ],
                "iDisplayLength": 10,
                "language": {
                    search: ""
                }
            });
            $('#dataTable').each(function () {
                var datatable = $(this);
                // SEARCH - Add the placeholder for Search and Turn this into in-line form control
                var search_input = datatable.closest('.dataTables_wrapper').find('div[id$=_filter] input');
                search_input.attr('placeholder', 'Search');
                search_input.removeClass('form-control-sm');
                // LENGTH - Inline-Form control
                var length_sel = datatable.closest('.dataTables_wrapper').find('div[id$=_length] select');
                length_sel.removeClass('form-control-sm');
            });
        });

    });
</script>
{% endblock %}