app/models/qams.py
from .. import db
from datetime import datetime
from flask import current_app
from app.models.roles import Role


class Qam(db.Model):
    __tablename__ = "qams"
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(120))
    user_id = db.Column(db.Integer(), db.ForeignKey("users.id"))
    createdAt = db.Column(db.DateTime(), default=datetime.utcnow)
    updatedAt = db.Column(
        db.DateTime(), default=datetime.utcnow, onupdate=datetime.utcnow
    )

    def __repr__(self):
        return '<Qam \'%s\'>' % self.title

app/qam/forms.py
from flask import url_for
from flask_wtf import Form, FlaskForm
from wtforms.ext.sqlalchemy.fields import QuerySelectField, QuerySelectMultipleField
from wtforms import ValidationError
from wtforms.fields import (
    BooleanField,
    PasswordField,
    StringField,
    SubmitField,
    TextField,
    DateField,
    DecimalField,
    SelectField,
    TextAreaField,
    IntegerField,
    FileField)
from wtforms import RadioField
from wtforms.fields.html5 import EmailField
from wtforms.validators import Email, EqualTo, InputRequired, Length, DataRequired
from flask_wtf.file import FileField, FileRequired, FileAllowed
from flask_uploads import UploadSet, configure_uploads, DOCUMENTS, IMAGES, TEXT
from flask_login import current_user
from app.models import User
from app.models import *

certificates = UploadSet("certificates", TEXT + DOCUMENTS + IMAGES)


def get_pk(obj):
    return str(obj)


class ProfileForm(FlaskForm):
    first_name = StringField(
        'First name', validators=[InputRequired(),
                                  Length(1, 64)])
    surname = StringField(
        'Surname', validators=[InputRequired(),
                               Length(1, 64)])
    email = EmailField(
        'Email', validators=[InputRequired(),
                             Length(1, 64),
                             Email()])
    address = StringField('Address')
    dob = DateField('Date Of Birth', validators=[DataRequired()], format='%d/%m/%Y')

    submit = SubmitField('Submit')


class FileForm(FlaskForm):
    subject = TextAreaField('Subject')
    reference_number = StringField(
        'Reference Number', validators=[InputRequired(),
                                        Length(1, 64)])

    date_modified = DateField('Date', validators=[DataRequired()], format='%d/%m/%Y')

    submit = SubmitField('Submit')


class MemoForm(FlaskForm):
    author_id = IntegerField('Author')
    title = TextAreaField('Title')
    reference_number = StringField(
        'Reference Number', validators=[InputRequired(),
                                        Length(1, 64)])

    date_modified = DateField('Date', validators=[DataRequired()], format='%d/%m/%Y')

    submit = SubmitField('Submit')


class AssignFileForm(FlaskForm):
    file = QuerySelectField(
        'File',
        validators=[InputRequired()],
        get_label='subject',
        query_factory=lambda: db.session.query(File).order_by('updatedAt'), get_pk=get_pk)
    folio = IntegerField('Folio')
    submit = SubmitField('Add Memo To File')

    # def validate_file(self, field):
    #     memo = Memo.query.filter_by(file_id=field.data.id).first()
    #     file = File.query.filter_by(id=field.data.id).first()
    #     if memo:
    #         raise ValidationError("Memo already assigned to a file.")


class AuthorForm(FlaskForm):
    name = TextAreaField('Name')
    submit = SubmitField('Submit')


class RecipientForm(FlaskForm):
    recipient_name = StringField('Recipient Name')
    memo_id = IntegerField('Memo')
    recipient = QuerySelectField(
        'Recipient',
        validators=[InputRequired()],
        get_label='first_name',
        query_factory=lambda: db.session.query(User).filter_by(role_id=1).order_by('first_name'), get_pk=get_pk)
    submit = SubmitField('Submit')


class CommentForm(FlaskForm):
    comment_body = TextAreaField(
        'Comment Body')
    recipient_id = QuerySelectField(
        'Recipient',
        get_label='first_name',
        query_factory=lambda: db.session.query(User).filter_by(role_id=2).order_by('first_name'), get_pk=get_pk)
    submit = SubmitField('Add')


class ChangeUserEmailForm(FlaskForm):
    email = EmailField(
        "New email", validators=[InputRequired(), Length(1, 64), Email()]
    )
    submit = SubmitField("Update email")

    def validate_email(self, field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError("Email already registered.")


class ChangeAccountTypeForm(FlaskForm):
    role = QuerySelectField(
        'New account type',
        validators=[InputRequired()],
        get_label='name',
        query_factory=lambda: db.session.query(Role).order_by('permissions'), get_pk=get_pk)
    submit = SubmitField('Update role')


class InviteUserForm(FlaskForm):
    role = QuerySelectField(
        'Account type',
        validators=[InputRequired()],
        get_label='name',
        query_factory=lambda: db.session.query(Role).order_by('permissions'), get_pk=get_pk)
    first_name = StringField("First name", validators=[InputRequired(), Length(1, 64)])
    second_name = StringField("Last name", validators=[InputRequired(), Length(1, 64)])
    email = EmailField("Email", validators=[InputRequired(), Length(1, 64), Email()])
    submit = SubmitField("Invite")

    def validate_email(self, field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError("Email already registered.")


class NewUserForm(InviteUserForm):
    password = PasswordField("Password", validators=[InputRequired()])
    password2 = PasswordField(
        "Confirm password",
        validators=[InputRequired(), EqualTo("password", "Passwords must match.")],
    )

    submit = SubmitField("Create")

app/qam/__init__.py
from app.qam.views import qam

app/qam/views.py
from flask import (
    Blueprint,
    render_template,
    redirect,
    url_for,
    jsonify,
    flash,
    send_from_directory,
)
from flask_ckeditor import upload_success
from flask_login import (
    current_user,
    login_required,
)
import PIL, simplejson, traceback
from PIL import Image
from flask_rq import get_queue

from app.models.users import *
from app.qam.forms import *
from app.auth.forms import *
from app import db
from app.email import send_email
from app.models import User, Message
from app.auth.email import send_password_reset_email
from app.auth.admin_decorators import check_confirmed
from app.decorators import qam_required
from werkzeug import secure_filename
from app.lib.upload_file import uploadfile
from werkzeug.datastructures import FileStorage

ALLOWED_EXTENSIONS = {"txt", "gif", "png", "jpg", "jpeg", "bmp", "rar", "zip", "7zip", "doc", "docx", "pdf"}

qam = Blueprint('qam', __name__)
certificates = UploadSet("certificates", TEXT + DOCUMENTS + IMAGES)


@qam.route('/')
@login_required
@check_confirmed
def dashboard():
    """Admin dashboard page."""
    sen_memos = Memo.query.filter_by(author_id=current_user.id).order_by(Memo.createdAt.desc()).limit(4)
    all_memos_sent = Memo.query.filter_by(author_id=current_user.id).all()
    recs = Recipient.query.join(User, (User.id == Recipient.user_id)).filter(User.id == current_user.id) \
        .order_by(Recipient.createdAt.desc()).limit(4)
    open_memos = Memo.query.filter_by(author_id=current_user.id, status='Open').all()

    return render_template('author/index.html', sen_memos=sen_memos, recs=recs, open_memos=open_memos)


@qam.route("/view_all_files")
@login_required
@check_confirmed
def view_all_files():
    """All files page."""
    all_files = File.query.order_by(File.createdAt.desc()).all()
    first_recipient = Recipient.query.join(Memo, (Memo.id == Recipient.memo_id)).first()
    memo_recipients = Recipient.query.join(Memo, (Memo.id == Recipient.memo_id)).all()
    return render_template(
        "qam/all_files.html", all_files=all_files,
        first_recipient=first_recipient, memo_recipients=memo_recipients)


@qam.route('/view_file/<file_id>', methods=['post', 'get'])
@login_required
@check_confirmed
def view_file(file_id):
    file = File.query.filter_by(public_id=file_id).first_or_404()
    file_memos = Memo.query.filter_by(file_id=file.id).order_by(Memo.updatedAt.desc()).all()

    memo = Memo
    comment = Comment
    user = User
    recipient = Recipient

    return render_template('qam/view_file.html', file=file, memo=memo, recipient=recipient,
                           comment=comment, user=user,
                           file_memos=file_memos)


@qam.route('/my_files/close_cycle/<file_id>', methods=['post', 'get'])
@login_required
@qam_required
@check_confirmed
def close_file_cycle(file_id):
    closed_file = File.query.filter_by(public_id=file_id).first_or_404()
    if closed_file.status == 'Open':
        closed_file.status = 'Closed'
    else:
        closed_file.status = 'Open'
    db.session.commit()
    flash("Successfully updated memo status", "success")
    return redirect(url_for("qam.view_all_files"))


@qam.route('/new_file', methods=['post', 'get'])
@login_required
@check_confirmed
def new_file():
    """Create file."""
    form = FileForm()
    if form.validate_on_submit():
        file = File(
            public_id=str(uuid.uuid4()),
            subject=form.subject.data,
            reference_number=form.reference_number.data,
            date_modified=form.date_modified.data
        )
        db.session.add(file)
        db.session.commit()
        flash('Successfully added File!', 'success')
        return redirect(url_for('qam.view_all_files'))
    return render_template('qam/add_new_file.html', form=form)


@qam.route("/view_all_memos")
@login_required
@check_confirmed
def view_all_memos():
    """All memos page."""
    all_memos = Memo.query.order_by(Memo.createdAt.desc()).all()
    first_recipient = Recipient.query.join(Memo, (Memo.id == Recipient.memo_id)).first()
    memo_recipients = Recipient.query.join(Memo, (Memo.id == Recipient.memo_id)).all()
    screams = Memo.query.join(Recipient, (Recipient.memo_id == Memo.id)) \
        .filter(Recipient.user_id == current_user.id).all()
    cb = Recipient
    return render_template(
        "qam/all_memos.html", all_memos=all_memos,
        first_recipient=first_recipient, memo_recipients=memo_recipients, cb=cb)


@qam.route("/memos_by_author")
@login_required
@check_confirmed
def memos_by_author():
    """All memos page."""
    all_memos = Memo.query.order_by(Memo.createdAt.desc()).all()
    all_users = User.query.filter_by(role_id=2).all()
    first_recipient = Recipient.query.join(Memo, (Memo.id == Recipient.memo_id)).first()
    memo_recipients = Recipient.query.join(Memo, (Memo.id == Recipient.memo_id)).all()
    cb = Recipient
    return render_template(
        "qam/memos_by_author.html", all_memos=all_memos,
        first_recipient=first_recipient, memo_recipients=memo_recipients, all_users=all_users, cb=cb)


@qam.route("/memos_by_recipient")
@login_required
@check_confirmed
def memos_by_recipient():
    """All memos page."""
    all_memos = Memo.query.order_by(Memo.createdAt.desc()).all()
    all_users = User.query.all()
    first_recipient = Recipient.query.join(Memo, (Memo.id == Recipient.memo_id)).first()
    memo_recipients = Recipient.query.join(Memo, (Memo.id == Recipient.memo_id)).all()
    screams = Memo.query.join(Recipient, (Recipient.memo_id == Memo.id)) \
        .filter(Recipient.user_id == current_user.id).all()
    cb = Recipient
    return render_template(
        "qam/memos_by_recipient.html", all_memos=all_memos,
        first_recipient=first_recipient, memo_recipients=memo_recipients, all_users=all_users,
        screams=screams, cb=cb)


@qam.route('/new_memo', methods=['post', 'get'])
@login_required
@check_confirmed
def new_memo():
    """Create memo."""
    form = MemoForm()
    if form.validate_on_submit():
        memo = Memo(
            public_id=str(uuid.uuid4()),
            memo_title=form.title.data,
            author_id=current_user.id,
            reference_number=form.reference_number.data,
            date_modified=form.date_modified.data
        )
        db.session.add(memo)
        db.session.commit()
        flash('Successfully added memo! Please indicate the recipient of this memo', 'success')
        return redirect(url_for('author.new_memo_assign', memo_id=memo.public_id))
    return render_template('author/add_new_memo.html', form=form)


@qam.route('/new_memo/assign_recipient_zero/<memo_id>', methods=['post', 'get'])
@login_required
@check_confirmed
def new_memo_assign(memo_id):
    """Assign memo."""
    memo = Memo.query.filter_by(public_id=memo_id).first_or_404()
    form = RecipientForm()
    this_recipient = form.recipient.data
    if form.validate_on_submit():
        user = User.query.filter_by(id=this_recipient.id).first_or_404()
        recipient = Recipient(
            memo_id=memo.id,
            recipient_name=this_recipient.first_name,
            user_id=this_recipient.id
        )
        db.session.add(recipient)
        user.add_notification('unread_memo_count', user.new_memos())
        db.session.commit()
        flash('Successfully added recipient to memo', 'success')
        return redirect(url_for('author.sent_memos'))
    return render_template('author/assign_recipient.html', form=form, memo=memo)


@qam.route('/new_file/assign_memo_file/<memo_id>', methods=['post', 'get'])
@login_required
@check_confirmed
def new_file_assign(memo_id):
    """Assign file."""
    memo = Memo.query.filter_by(public_id=memo_id).first_or_404()
    form = AssignFileForm()
    this_file = form.file.data
    if form.validate_on_submit():
        memo.file_id = this_file.id
        memo.folio = form.folio.data
        db.session.commit()
        flash('Successfully added memo to file {}'.format(this_file.subject), 'success')
        return redirect(url_for('qam.view_all_memos'))
    return render_template('qam/assign_file.html', form=form, memo=memo)


@qam.route('/view_memo/<memo_id>', methods=['post', 'get'])
@login_required
@check_confirmed
def view_memo(memo_id):
    """View memo."""
    memo = Memo.query.filter_by(public_id=memo_id).first_or_404()
    first_recipient = Recipient.query.join(Memo, (Memo.id == Recipient.memo_id)).filter(
        Memo.public_id == memo_id).first()
    memo_recipients = Recipient.query.join(Memo, (Memo.id == Recipient.memo_id)).all()
    memo_comments = Comment.query.join(User, (User.id == Comment.user_id)).filter(Comment.memo_id == memo.id).all()
    date_added = memo.createdAt
    date_modified = memo.date_modified
    da = date_added.strftime('%d/%m/%Y')
    dm = date_modified.strftime('%d/%m/%Y')
    current_user.last_memo_read_time = datetime.utcnow()
    current_user.last_comment_read_time = datetime.utcnow()
    current_user.add_notification('unread_memo_count', 0)
    current_user.add_notification('unread_comment_count', 0)
    db.session.commit()

    return render_template('qam/view_memo.html', memo=memo, da=da, dm=dm,
                           memo_recipients=memo_recipients, first_recipient=first_recipient,
                           memo_comments=memo_comments)


@qam.route('/my_memos/received', methods=['post', 'get'])
@login_required
@check_confirmed
def received_memos():
    current_user.last_memo_read_time = datetime.utcnow()
    current_user.last_comment_read_time = datetime.utcnow()
    current_user.add_notification('unread_memo_count', 0)
    current_user.add_notification('unread_comment_count', 0)
    db.session.commit()
    recs = Recipient.query.join(User, (User.id == Recipient.user_id)).filter(User.id == current_user.id) \
        .order_by(Recipient.createdAt.desc()).all()
    screams = Memo.query.join(Recipient, (Recipient.memo_id == Memo.id)) \
        .filter(Recipient.user_id == current_user.id).all()

app/templates/qam/add_new_file.html
{% extends 'layouts/base.html' %}
{% block custom_head_tags %}
<!-- CORE CSS-->
<link rel="stylesheet"
      href="{{ url_for('static', filename='vendors/bootstrap-datepicker/bootstrap-datepicker.min.css') }}">

{% endblock %}

{% block content %}
<nav class="page-breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#">CREATE</a></li>
        <li class="breadcrumb-item active" aria-current="page">New File</li>
    </ol>
</nav>

<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <form class="cmxform" method="post" action="{{url_for('qam.new_file')}}">
                    {{form.hidden_tag()}}
                    <div class="row">
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label>Subject *</label>
                                {{form.subject(placeholder="Subject", class="form-control")}}
                                {%for error in form.subject.errors%}
                                <span class="text-danger">{{error}}</span>
                                {%endfor%}
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label>Reference Number *</label>
                                {{form.reference_number(placeholder="Reference Number", class="form-control")}}
                                {%for error in form.reference_number.errors%}
                                <span class="text-danger">{{error}}</span>
                                {%endfor%}
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label>Date </label>
                                <div class="input-group date datepicker" id="datePicker"
                                style="margin-bottom: 1rem;" data-date-format="dd/mm/yyyy">
                                    {{form.date_modified(class="form-control")}}
                                    <span class="input-group-addon"><i
                                            data-feather="calendar"></i></span>
                                    {%for error in form.date_modified.errors%}
                                    <span class="text-danger">{{error}}</span>
                                    {%endfor%}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-4">
                            {{form.submit(class="btn btn-primary mr-2 mb-2 mb-md-0 text-white")}}
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


{% endblock %}
{% block scripts%}
    <script>
            $(function() {
      'use strict';

      if($('#datePicker').length) {
        var date = new Date();
        var today = new Date(date.getFullYear(), date.getMonth(), date.getDate());
        $('#datePicker').datepicker({
          format: "dd/mm/yyyy",
          todayHighlight: true,
          autoclose: true
        });

        $('#datePicker').datepicker('setDate', {%if m_date%}'{{m_date}}'{%else%} today {%endif%});
      }
    });
    </script>
{%  endblock %}

app/templates/qam/all_files.html
{% extends 'layouts/base.html' %}
{% block custom_head_tags %}
<!-- CORE CSS-->
<link rel="stylesheet"
      href="{{ url_for('static', filename='vendors/bootstrap-datepicker/bootstrap-datepicker.min.css') }}">
<!-- plugin css for this page -->
<link rel="stylesheet" href="{{ url_for('static', filename='vendors/prismjs/themes/prism.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='vendors/datatables.net-bs4/dataTables.bootstrap4.css') }}">
<!-- end plugin css for this page -->
{% endblock %}

{% block content %}
<div class="d-flex justify-content-between align-items-center flex-wrap grid-margin">
    <nav class="page-breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">VIEW</a></li>
            <li class="breadcrumb-item active" aria-current="page">All Files</li>
        </ol>
    </nav>
     <div class="d-flex align-items-center flex-wrap text-nowrap">
        <a href="{{ url_for('qam.new_file')}}" type="button" class="btn btn-primary">ADD FILE</a>
    </div>
</div>

<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <div class="d-flex justify-content-between align-items-baseline mb-lg-4">
                  <h6 class="card-title mb-0">All Files</h6>
                </div>
                <p class="card-description">Open Files are shown in green.</p>

                <div class="table-responsive">
                        <table id="dataTable" class="table table-hover mb-0">
                            <thead>
                            <tr>
                                <th class="pt-0">#</th>
                                <th class="pt-0">Reference Number</th>
                                <th class="pt-0">Subject</th>
                                <th class="pt-0">Status</th>
                                <th class="pt-0">Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for file in all_files %}
                            <tr  class="{% if file.status == 'Open' %}table-success{%endif%}">
                                <td>{{loop.index}}</td>
                                <td><a href="{{ url_for('qam.view_file', file_id=file.public_id) }}">{{file.reference_number}}</a>
                                </td>
                                </td>
                                <td>{{file.subject}}</td>
                                <td>
                                    {% if file.status == 'Open' %}
                                    <span class="badge badge-info-muted">Open</span>
                                    {%else%}
                                    <span class="badge badge-success">Closed</span>
                                    {% endif %}
                                </td>
                                <td>{% if file.status == 'Open' %}
                                    <a href="{{ url_for('qam.close_file_cycle', file_id=file.public_id) }}"
                                       class="btn btn-danger">Close</a>
                                    {% else %}
                                    <a href="{{ url_for('qam.close_file_cycle', file_id=file.public_id) }}"
                                       class="btn btn-success">Open</a>
                                    {%endif%}
                                </td>


                            </tr>
                            {% else %}
                            <tr>
                                <td><span style="color: #007bff;">No files available</span></td>
                            </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}
{% block scripts %}
<!-- plugin js for this page -->
<script src="{{ url_for('static', filename='vendors/prismjs/prism.js') }}"></script>
<script src="{{ url_for('static', filename='vendors/clipboard/clipboard.min.js') }}"></script>
<script src="{{ url_for('static', filename='vendors/datatables.net/jquery.dataTables.js') }}"></script>
<script src="{{ url_for('static', filename='vendors/datatables.net-bs4/dataTables.bootstrap4.js') }}"></script>
<!-- end plugin js for this page -->
<script>
    $(function () {
        'use strict';

        $(function () {
            $('#dataTable').DataTable({
                "aLengthMenu": [
                    [10, 30, 50, -1],
                    [10, 30, 50, "All"]
                ],
                "iDisplayLength": 10,
                "language": {
                    search: ""
                }
            });
            $('#dataTable').each(function () {
                var datatable = $(this);
                // SEARCH - Add the placeholder for Search and Turn this into in-line form control
                var search_input = datatable.closest('.dataTables_wrapper').find('div[id$=_filter] input');
                search_input.attr('placeholder', 'Search');
                search_input.removeClass('form-control-sm');
                // LENGTH - Inline-Form control
                var length_sel = datatable.closest('.dataTables_wrapper').find('div[id$=_length] select');
                length_sel.removeClass('form-control-sm');
            });
        });

    });
</script>
{% endblock %}

app/templates/qam/assign_file.html
{% extends 'layouts/base.html' %}
{% block custom_head_tags %}
<!-- CORE CSS-->
<link rel="stylesheet"
      href="{{ url_for('static', filename='vendors/bootstrap-datepicker/bootstrap-datepicker.min.css') }}">

{% endblock %}

{% block content %}
<nav class="page-breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#">ASSIGN</a></li>
        <li class="breadcrumb-item active" aria-current="page">Memo To File</li>
    </ol>
</nav>

<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <form class="cmxform" method="post" action="{{url_for('qam.new_file_assign', memo_id=memo.public_id)}}">
                    {{form.hidden_tag()}}
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label>Folio</label>
                                {{form.folio(placeholder="Folio", class="form-control")}}
                                {%for error in form.folio.errors%}
                                <span class="text-danger">{{error}}</span>
                                {%endfor%}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label>File</label>
                                {{form.file(placeholder="File", class="form-control")}}
                                {%for error in form.file.errors%}
                                <span class="text-danger">{{error}}</span>
                                {%endfor%}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-4">
                            {{form.submit(class="btn btn-primary mr-2 mb-2 mb-md-0 text-white")}}
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


{% endblock %}
{% block scripts%}
    <script>
            $(function() {
      'use strict';

      if($('#datePicker').length) {
        var date = new Date();
        var today = new Date(date.getFullYear(), date.getMonth(), date.getDate());
        $('#datePicker').datepicker({
          format: "dd/mm/yyyy",
          todayHighlight: true,
          autoclose: true
        });

        $('#datePicker').datepicker('setDate', {%if m_date%}'{{m_date}}'{%else%} today {%endif%});
      }
    });
    </script>
{%  endblock %}

app/templates/qam/forward_memo.html
{% extends 'layouts/base.html' %}
{% block custom_head_tags %}
<!-- CORE CSS-->
<link rel="stylesheet"
      href="{{ url_for('static', filename='vendors/bootstrap-datepicker/bootstrap-datepicker.min.css') }}">

{% endblock %}

{% block content %}
<nav class="page-breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#">CREATE</a></li>
        <li class="breadcrumb-item active" aria-current="page">New Comment for {{memo.reference_number}}</li>
    </ol>
</nav>

<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <form class="cmxform" method="post" action="{{url_for('qam.add_comment', memo_id=memo.public_id)}}">
                    {{form.hidden_tag()}}
                    <div class="row">
                        <div class="col-sm-8">
                            <div class="form-group">
                                <label>Comment *</label>
                                {{form.comment_body(placeholder="Comment", class="form-control")}}
                                {%for error in form.comment_body.errors%}
                                <span class="text-danger">{{error}}</span>
                                {%endfor%}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-8">
                            <div class="form-group">
                                <label>Forward To</label>
                                {{form.recipient_id(placeholder="Forward TO", class="form-control")}}
                                {%for error in form.recipient_id.errors%}
                                <span class="text-danger">{{error}}</span>
                                {%endfor%}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-4">
                            {{form.submit(class="btn btn-primary mr-2 mb-2 mb-md-0 text-white")}}
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


{% endblock %}
{% block scripts%}
    <script>
            $(function() {
      'use strict';

      if($('#datePicker').length) {
        var date = new Date();
        var today = new Date(date.getFullYear(), date.getMonth(), date.getDate());
        $('#datePicker').datepicker({
          format: "dd/mm/yyyy",
          todayHighlight: true,
          autoclose: true
        });

        $('#datePicker').datepicker('setDate', {%if m_date%}'{{m_date}}'{%else%} today {%endif%});
      }
    });
    </script>
{%  endblock %}